version: '3.7'
services:
  postgres:
    image: postgres:9
    ports:
      - 5432:5432
    container_name: db
    restart: always
    tty: true
    volumes:
      - "postgres:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=kotlin
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
volumes:
  postgres: