spring:
  datasource:
    url: jdbc:postgresql://localhost:55432/kotlin-poc
    username: root
    password: root
    driverClassName: org.postgresql.Driver
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.HSQLDialect
    hibernate.ddl-auto: update